// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTime.Repositories;

#nullable disable

namespace MyTime.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211219112618_AddPauseDuration")]
    partial class AddPauseDuration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("MyTime.Models.Database.WorkTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PauseDuration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
